###
GET http://localhost:3001/api/v1/blogs/

###
GET http://localhost:3001/api/v1/blogs/1

###
POST http://localhost:3001/api/v1/blogs/
Content-Type: application/json

{
    "title": "HeloooHellooooo",
    "author": "minuuuuu",
    "likes": -5,
    "url": "https://zod.dev/?id=optionals"
}

###
PUT http://localhost:3001/api/v1/blogs/12
Content-Type: application/json

{
    "title": ""
}

###
DELETE http://localhost:3001/api/v1/blogs/5

###
GET http://localhost:3001/api/v1/users/

###
GET http://localhost:3001/api/v1/users/13

###
POST http://localhost:3001/api/v1/users/
Content-Type: application/json

{
    "name": "Lizan",
    "email": "lizan@gmail.com",
    "password": "LizanMah@1",
    "image": "Lizan Image"
}

###
PUT http://localhost:3001/api/v1/users/1
Content-Type: application/json

{
    "roles": "ADMIN"
}

###
DELETE http://localhost:3001/api/v1/users/6

###
POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
    "email": "lizna@gmail.com",
    "password": "LiznaMah@1"
}
