###
GET http://localhost:3001/api/v1/blogs/

###
GET http://localhost:3001/api/v1/blogs/1

###
POST http://localhost:3001/api/v1/blogs/
Content-Type: application/json

{
    "title": "My Journey",
    "author": "Sharmila",
    "likes": 8,
    "url": "sharmi.com.np"
}

###
PUT http://localhost:3001/api/v1/blogs/6
Content-Type: application/json

{
    "title": "My Journey",
    "author": "Sharmila",
    "likes": 8,
    "url": "sharmijirel.com.np"
}

###
DELETE http://localhost:3001/api/v1/blogs/5
